name: Sync Forked Repos

on:
  schedule:
    - cron: '0 16 * * *' # 每天 UTC 时间 16:00（即北京时间凌晨 00:00）运行一次
  workflow_dispatch: # 手动触发工作流

jobs:
  sync-forks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set timezone to Asia/Shanghai
        run: |
          echo "Setting timezone to Asia/Shanghai"
          sudo timedatectl set-timezone Asia/Shanghai

      - name: Display current time
        run: |
          echo "Current time in Beijing: $(date)"

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Run the Sync Forked Repos script
        run: |
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] Fetching the list of repositories for OWNER: $OWNER..."
            repos=$(gh repo list "$OWNER" --limit 200 --json nameWithOwner,isFork)
            
            # 初始化错误计数器和仓库列表
            error_count=0
            failed_repos=()
            updated_repos=()
            
            for repo in $(echo "$repos" | jq -c '.[]'); do
                nameWithOwner=$(echo "$repo" | jq -r '.nameWithOwner')
                isFork=$(echo "$repo" | jq -r '.isFork')
                
                if [ "$isFork" = "true" ]; then
                    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Syncing forked repository: $nameWithOwner..."
                    
                    # 捕获 gh repo sync 的输出
                    if output=$(gh repo sync "$nameWithOwner" 2>&1); then
                        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Successfully synced: $nameWithOwner"
                        # 检查输出中是否包含 "fast-forward" 来判断是否有更新
                        if [[ $output == *"fast-forward"* ]]; then
                            updated_repos+=("$nameWithOwner")
                        fi
                    else
                        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Failed to sync: $nameWithOwner" >&2
                        error_count=$((error_count + 1))
                        failed_repos+=("$nameWithOwner")
                    fi
                fi
            done
            
            # 检查是否有同步失败的仓库
            echo ""
            echo "--------------------------------"
            # 先显示更新的仓库
            if [ ${#updated_repos[@]} -gt 0 ]; then
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Repositories with updates from upstream:"
                printf '%s\n' "${updated_repos[@]}"
                echo ""
            fi
            
            # 显示失败的仓库
            if [ $error_count -gt 0 ]; then
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] Sync completed with $error_count failures"
                echo "Failed repositories:"
                printf '%s\n' "${failed_repos[@]}"
                exit 1
            else
                echo "[$(date '+%Y-%m-%d %H:%M:%S')] All repositories synced successfully"
            fi
            echo "--------------------------------"

        env:
            GH_TOKEN: ${{ secrets.SYNC_GITHUB_TOKEN }}
            OWNER: ${{ github.repository_owner }}
