name: Sync Forked Repos

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜 00:00 运行一次
  workflow_dispatch: # 手动触发工作流

jobs:
  sync-forks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Run sync-repos.sh script
        run: | 
            echo "Fetching the list of repositories for OWNER: $OWNER..."
            repos=$(gh repo list "$OWNER" --limit 200 --json nameWithOwner,isFork)

            for repo in $(echo "$repos" | jq -c '.[]'); do
            nameWithOwner=$(echo "$repo" | jq -r '.nameWithOwner')
            isFork=$(echo "$repo" | jq -r '.isFork')
            
            if [ "$isFork" = "true" ]; then
                echo "Syncing forked repository: $nameWithOwner"
                gh repo sync "$nameWithOwner"
            else
                echo "Skipping non-fork repository: $nameWithOwner"
            fi
            done
        env:
            GH_TOKEN: ${{ secrets.SYNC_GITHUB_TOKEN }}
            OWNER: ${{ github.repository_owner }}
